package trikita.anvil.constraint.layout;

import android.support.constraint.Barrier;
import android.support.constraint.ConstraintHelper;
import android.support.constraint.ConstraintLayout;
import android.support.constraint.Constraints;
import android.support.constraint.Group;
import android.support.constraint.Guideline;
import android.support.constraint.Placeholder;
import android.view.View;
import java.lang.Float;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import trikita.anvil.Anvil;
import trikita.anvil.BaseDSL;

/**
 * DSL for creating views and settings their attributes.
 * This file has been generated by {@code gradle generateConstraintDSL}.
 * It contains views and their setters from the library constraint-layout.
 * Please, don't edit it manually unless for debugging.
 */
public final class ConstraintDSL implements Anvil.AttributeSetter {
  static {
    Anvil.registerAttributeSetter(new ConstraintDSL());
  }

  public static BaseDSL.ViewClassResult barrier() {
    return BaseDSL.v(Barrier.class);
  }

  public static Void barrier(Anvil.Renderable r) {
    return BaseDSL.v(Barrier.class, r);
  }

  public static BaseDSL.ViewClassResult constraintHelper() {
    return BaseDSL.v(ConstraintHelper.class);
  }

  public static Void constraintHelper(Anvil.Renderable r) {
    return BaseDSL.v(ConstraintHelper.class, r);
  }

  public static BaseDSL.ViewClassResult constraintLayout() {
    return BaseDSL.v(ConstraintLayout.class);
  }

  public static Void constraintLayout(Anvil.Renderable r) {
    return BaseDSL.v(ConstraintLayout.class, r);
  }

  public static BaseDSL.ViewClassResult constraints() {
    return BaseDSL.v(Constraints.class);
  }

  public static Void constraints(Anvil.Renderable r) {
    return BaseDSL.v(Constraints.class, r);
  }

  public static BaseDSL.ViewClassResult group() {
    return BaseDSL.v(Group.class);
  }

  public static Void group(Anvil.Renderable r) {
    return BaseDSL.v(Group.class, r);
  }

  public static BaseDSL.ViewClassResult guideline() {
    return BaseDSL.v(Guideline.class);
  }

  public static Void guideline(Anvil.Renderable r) {
    return BaseDSL.v(Guideline.class, r);
  }

  public static BaseDSL.ViewClassResult placeholder() {
    return BaseDSL.v(Placeholder.class);
  }

  public static Void placeholder(Anvil.Renderable r) {
    return BaseDSL.v(Placeholder.class, r);
  }

  public static Void contentId(int arg) {
    return BaseDSL.attr("contentId", arg);
  }

  public static Void emptyVisibility(int arg) {
    return BaseDSL.attr("emptyVisibility", arg);
  }

  public static Void guidelineBegin(int arg) {
    return BaseDSL.attr("guidelineBegin", arg);
  }

  public static Void guidelineEnd(int arg) {
    return BaseDSL.attr("guidelineEnd", arg);
  }

  public static Void guidelinePercent(float arg) {
    return BaseDSL.attr("guidelinePercent", arg);
  }

  public boolean set(View v, String name, final Object arg, final Object old) {
    switch (name) {
      case "contentId":
        if (v instanceof Placeholder && arg instanceof Integer) {
          ((Placeholder) v).setContentId((int) arg);
          return true;
        }
        break;
      case "emptyVisibility":
        if (v instanceof Placeholder && arg instanceof Integer) {
          ((Placeholder) v).setEmptyVisibility((int) arg);
          return true;
        }
        break;
      case "guidelineBegin":
        if (v instanceof Guideline && arg instanceof Integer) {
          ((Guideline) v).setGuidelineBegin((int) arg);
          return true;
        }
        break;
      case "guidelineEnd":
        if (v instanceof Guideline && arg instanceof Integer) {
          ((Guideline) v).setGuidelineEnd((int) arg);
          return true;
        }
        break;
      case "guidelinePercent":
        if (v instanceof Guideline && arg instanceof Float) {
          ((Guideline) v).setGuidelinePercent((float) arg);
          return true;
        }
        break;
    }
    return false;
  }
}
